import { Product } from '../models/product.model';

// Mirrors public/assets/sample-data/*.csv so the demo starts with the same
// catalogue the backend would hold after importing every sample file.
export const DEMO_CATALOG: Product[] = [
  { id: 'demo-001', category: 'vinyl', price: 36.99, imageUrl: 'assets/products/pf-animals.jpg', attributes: {"artist": "Pink Floyd", "title": "Animals"} },
  { id: 'demo-002', category: 'vinyl', price: 31.99, imageUrl: 'assets/products/black-sabbath-vol4.jpg', attributes: {"artist": "Black Sabbath", "title": "Vol. 4"} },
  { id: 'demo-003', category: 'vinyl', price: 38.99, imageUrl: 'assets/products/beatles-abbey-road.jpg', attributes: {"artist": "The Beatles", "title": "Abbey Road"} },
  { id: 'demo-004', category: 'vinyl', price: 34.99, imageUrl: 'assets/products/led-zeppelin-iv.jpg', attributes: {"artist": "Led Zeppelin", "title": "IV"} },
  { id: 'demo-005', category: 'vinyl', price: 39.99, imageUrl: 'assets/products/king-crimson-in-the-court.jpg', attributes: {"artist": "King Crimson", "title": "In the Court of the Crimson King"} },
  { id: 'demo-006', category: 'vinyl', price: 29.99, imageUrl: 'assets/products/acdc-let-there-be-rock.jpg', attributes: {"artist": "AC/DC", "title": "Let There Be Rock"} },
  { id: 'demo-007', category: 'vinyl', price: 32.99, imageUrl: 'assets/products/thin-lizzy-jailbreak.jpg', attributes: {"artist": "Thin Lizzy", "title": "Jailbreak"} },
  { id: 'demo-008', category: 'vinyl', price: 33.99, imageUrl: 'assets/products/deep-purple-machine-head.jpg', attributes: {"artist": "Deep Purple", "title": "Machine Head"} },
  { id: 'demo-009', category: 'vinyl', price: 35.99, imageUrl: 'assets/products/rolling-stones-sticky-fingers.jpg', attributes: {"artist": "Rolling Stones", "title": "Sticky Fingers"} },
  { id: 'demo-010', category: 'vinyl', price: 33.99, imageUrl: 'assets/products/dire-straits-making-movies.jpg', attributes: {"artist": "Dire Straits", "title": "Making Movies"} },
  { id: 'demo-011', category: 'vinyl', price: 35.99, imageUrl: 'assets/products/van-halen-1984.jpg', attributes: {"artist": "Van Halen", "title": "1984"} },
  { id: 'demo-012', category: 'vinyl', price: 32.99, imageUrl: 'assets/products/scorpions-blackout.jpg', attributes: {"artist": "Scorpions", "title": "Blackout"} },
  { id: 'demo-013', category: 'vinyl', price: 33.99, imageUrl: 'assets/products/zz-top-eliminator.jpg', attributes: {"artist": "ZZ Top", "title": "Eliminator"} },
  { id: 'demo-014', category: 'vinyl', price: 34.99, imageUrl: 'assets/products/the-police-synchronicity.jpg', attributes: {"artist": "The Police", "title": "Synchronicity"} },
  { id: 'demo-015', category: 'vinyl', price: 36.99, imageUrl: 'assets/products/guns-n-roses-appetite-for-destruction.jpg', attributes: {"artist": "Guns N' Roses", "title": "Appetite For Destruction"} },
  { id: 'demo-016', category: 'vinyl', price: 33.99, imageUrl: 'assets/products/def-leppard-pyromania.jpg', attributes: {"artist": "Def Leppard", "title": "Pyromania"} },
  { id: 'demo-017', category: 'vinyl', price: 35.99, imageUrl: 'assets/products/bon-jovi-slippery-when-wet.jpg', attributes: {"artist": "Bon Jovi", "title": "Slippery When Wet"} },
  { id: 'demo-018', category: 'vinyl', price: 29.99, imageUrl: 'assets/products/queen-hot-space.jpg', attributes: {"artist": "Queen", "title": "Hot Space"} },
  { id: 'demo-019', category: 'vinyl', price: 34.99, imageUrl: 'assets/products/u2-the-joshua-tree.jpg', attributes: {"artist": "U2", "title": "The Joshua Tree"} },
  { id: 'demo-020', category: 'vinyl', price: 34.99, imageUrl: 'assets/products/dire-straits-brothers-in-arms.jpg', attributes: {"artist": "Dire Straits", "title": "Brothers In Arms"} },
  { id: 'demo-021', category: 'vinyl', price: 34.99, imageUrl: 'assets/products/black-sabbath-heaven-and-hell.jpg', attributes: {"artist": "Black Sabbath", "title": "Heaven And Hell"} },
  { id: 'demo-022', category: 'vinyl', price: 32.99, imageUrl: 'assets/products/iron-maiden-iron-maiden.jpg', attributes: {"artist": "Iron Maiden", "title": "Iron Maiden"} },
  { id: 'demo-023', category: 'vinyl', price: 36.99, imageUrl: 'assets/products/metallica-master-of-puppets.jpg', attributes: {"artist": "Metallica", "title": "Master Of Puppets"} },
  { id: 'demo-024', category: 'vinyl', price: 33.99, imageUrl: 'assets/products/pantera-cowboys-from-hell.jpg', attributes: {"artist": "Pantera", "title": "Cowboys From Hell"} },
  { id: 'demo-025', category: 'vinyl', price: 34.99, imageUrl: 'assets/products/megadeth-rust-in-peace.jpg', attributes: {"artist": "Megadeth", "title": "Rust In Peace"} },
  { id: 'demo-026', category: 'vinyl', price: 31.99, imageUrl: 'assets/products/dio-holy-diver.jpg', attributes: {"artist": "Dio", "title": "Holy Diver"} },
  { id: 'demo-027', category: 'vinyl', price: 30.99, imageUrl: 'assets/products/slayer-reign-in-blood.jpg', attributes: {"artist": "Slayer", "title": "Reign In Blood"} },
  { id: 'demo-028', category: 'vinyl', price: 32.99, imageUrl: 'assets/products/judas-priest-british-steel.jpg', attributes: {"artist": "Judas Priest", "title": "British Steel"} },
  { id: 'demo-029', category: 'vinyl', price: 31.99, imageUrl: 'assets/products/iron-maiden-killers.jpg', attributes: {"artist": "Iron Maiden", "title": "Killers"} },
  { id: 'demo-030', category: 'vinyl', price: 34.99, imageUrl: 'assets/products/metallica-kill-em-all.jpg', attributes: {"artist": "Metallica", "title": "Kill 'Em All"} },
  { id: 'demo-031', category: 'turntable', price: 1925.0, imageUrl: 'assets/products/Rega-Planar-6.webp', attributes: {"manufacturer": "Rega", "name": "Planar 6"} },
  { id: 'demo-032', category: 'turntable', price: 599.0, imageUrl: 'assets/products/ProJect-T1-EVO-Phono.webp', attributes: {"manufacturer": "Pro-Ject", "name": "T1 EVO Phono"} },
  { id: 'demo-033', category: 'turntable', price: 719.0, imageUrl: 'assets/products/Denon-DP-450USB.webp', attributes: {"manufacturer": "Denon", "name": "DP-450USB"} },
  { id: 'demo-034', category: 'turntable', price: 299.0, imageUrl: 'assets/products/Pioneer-PL-30-K.webp', attributes: {"manufacturer": "Pioneer", "name": "PL-30-K"} },
  { id: 'demo-035', category: 'turntable', price: 499.0, imageUrl: 'assets/products/Music-Hall-MMF-2.3.webp', attributes: {"manufacturer": "Music Hall", "name": "MMF-2.3"} },
  { id: 'demo-036', category: 'turntable', price: 1199.0, imageUrl: 'assets/products/NAD-C588.webp', attributes: {"manufacturer": "NAD", "name": "C588"} },
  { id: 'demo-037', category: 'turntable', price: 299.0, imageUrl: 'assets/products/Lenco-LBT-335.jpg', attributes: {"manufacturer": "Lenco", "name": "LBT-335"} },
  { id: 'demo-038', category: 'turntable', price: 1088.0, imageUrl: 'assets/products/ProJect-Debut-PRO-B.webp', attributes: {"manufacturer": "Pro-Ject", "name": "Debut PRO B"} },
  { id: 'demo-039', category: 'turntable', price: 800.0, imageUrl: 'assets/products/Dual-CS518.webp', attributes: {"manufacturer": "Dual", "name": "CS518"} },
  { id: 'demo-040', category: 'turntable', price: 1799.0, imageUrl: 'assets/products/Technics-SL-1210GR.webp', attributes: {"manufacturer": "Technics", "name": "SL-1210GR"} },
];
